name: Update Readme
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '15 04 * * *' # every 12:15 +08:00

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
        
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Update Readme
        run: python main.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - name: Commit and push
        run: |
          git diff
          git add .
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_NAME}"
          git commit -m "Updated README" -a
          git push
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
